feat(temp-kit): enhance functionality and improve template version
- Update temple version to 1.22.0
- Add minimum Go version requirement (1.21)
- Implement remote template version detection
- Improve logging with color options and debug level
- Fix typos and adjust usage message

diff --git a/temp-woodpecker-golang-plugin b/temp-woodpecker-golang-plugin
--- a/temp-woodpecker-golang-plugin
+++ b/temp-woodpecker-golang-plugin
@@ -1,13 +1,16 @@
 #!/usr/bin/env bash
 
-temple_version='1.21.2'
+temple_version='1.22.0'
 new_version_for_dev='1.0.0'
+go_minimum_version='1.21'
+
 #temple url
 temple_url="https://github.com/woodpecker-kit/woodpecker-plugin-env.git"
 temple_repo_host="github.com"
 temple_group="woodpecker-kit"
 temple_name="woodpecker-plugin-env"
 temple_branch="v${temple_version}"
+is_find_out_remote_temple_version=1
 
 new_repo_host=${temple_repo_host}
 new_repo_group=${temple_group}
@@ -19,9 +22,52 @@ shell_run_path=$(
   pwd
 )
 
+## need global var
+# will use global var
+# - is_find_out_remote_temple_version
+# will change global var
+# - temple_version
+# - temple_branch
+find_out_remote_temple_version() {
+  local remote_tag_url=$1
+  if [[ $is_find_out_remote_temple_version -eq 0 ]]; then
+    echo "-> pass find out remote latest version from repo: ${remote_tag_url}"
+    return 0
+  fi
+  # echo "=> start find out remote latest version from repo: ${remote_tag_url}"
+  local remote_tag_match='refs/tags/[^ ]*'
+  local remote_tag_sed_command='s#refs/tags/##'
+  local remote_latest_tag_name=$(git ls-remote --refs --tags ${remote_tag_url} | cut -f2 | grep -E "${remote_tag_match}" | sort -V | tail -n 1 | sed ${remote_tag_sed_command})
+  if [ ! $? -eq 0 ]; then
+    echo "not found remote latest tag by: ${remote_tag_url}"
+    return 1
+  else
+    # echo "remote_latest_tag_name=$remote_latest_tag_name"
+    # empty tag
+    if [[ -z "$remote_latest_tag_name" ]]; then
+      echo "-> remote tag is empty by: ${remote_tag_url}"
+      return 1
+    fi
+    if [[ $remote_latest_tag_name == v* ]]; then # Judge whether to start with v
+      temple_version=${remote_latest_tag_name:1}
+      temple_branch="v${temple_version}"
+    else
+      pW "remote latest tag not start with v, please check from: ${remote_tag_url}"
+      temple_version=${remote_latest_tag_name}
+      temple_branch="v${temple_version}"
+    fi
+  fi
+  # echo "-> find out remote tag info:"
+  # echo "temple_version =${temple_version}"
+  # echo "temple_branch  =${temple_branch}"
+  # echo "=> finish find out remote tag version"
+}
+
 function Usage() {
+  find_out_remote_temple_version ${temple_url}
   cat <<HELP
 ${shell_run_name} can use fast init golang lib project with github
+  Warning must use golang SDK ${go_minimum_version}+
   now template url is:  ${temple_url}
   now template version: ${temple_branch}
 
@@ -45,21 +91,53 @@ if [[ $# -eq 1 ]]; then
   fi
 fi
 
-pV() {
-  echo -e "\033[;36m$1\033[0m"
+# log debug enable 1 open 0 close
+LOG_DEBUG_ENABLE=1
+# log color enable 1 open 0 close
+LOG_COLOR_ENABLE=1
+
+pV(){
+  if [[ 0 -ne ${LOG_COLOR_ENABLE} ]]; then
+    echo -e "\033[;37m$1\033[0m"
+  else
+    echo -e "$1"
+  fi
 }
-pI() {
-  echo -e "\033[;32mINFO: $1\033[0m"
+pI(){
+  if [[ 0 -ne ${LOG_COLOR_ENABLE} ]]; then
+    echo -e "\033[;32mINFO: $1\033[0m"
+  else
+    echo -e "$1"
+  fi
 }
-pD() {
-  echo -e "\033[;34mDEBUG: $1\033[0m"
+pD(){
+  if [[ 0 -ne ${LOG_DEBUG_ENABLE} ]]; then
+    if [[ 0 -ne ${LOG_COLOR_ENABLE} ]]; then
+      echo -e "\033[;34mDEBUG: $1\033[0m"
+    else
+      echo -e "$1"
+    fi
+  fi
 }
-pW() {
-  echo -e "\033[;33mWARN: $1\033[0m"
+pW(){
+  if [[ 0 -ne ${LOG_COLOR_ENABLE} ]]; then
+    echo -e "\033[;33mWARN: $1\033[0m"
+  else
+    echo -e "$1"
+  fi
 }
-pE() {
-  echo -e "\033[;31mERROR: $1\033[0m"
+pE(){
+  if [[ 0 -ne ${LOG_COLOR_ENABLE} ]]; then
+    echo -e "\033[;31mERROR: $1\033[0m"
+  else
+    echo -e "$1"
+  fi
 }
+#pV "V"
+#pI "I"
+#pD "D"
+#pW "W"
+#pE "E"
 
 checkFuncBack() {
   if [ ! $? -eq 0 ]; then
@@ -239,6 +317,8 @@ fi
 temple_name_go_package=${temple_name//-/_}
 new_project_go_package=${new_project//-/_}
 
+find_out_remote_temple_version ${temple_url}
+
 echo -e "=> temple url: ${temple_url}
 => temple_branch:  ${temple_branch}
 -> new_repo_host:  ${new_repo_host}
@@ -329,7 +409,7 @@ mit*)
   mv ./${new_project}/LICENSE-APACHE ./${new_project}/LICENSE
   ;;
 esac
-# move other LICENCE
+# move other LICENSE
 removeFileByRegular "LICENSE-*"
 # replace LICENSE by git info
 license_template_user='{name[[:space:]]of[[:space:]]copyright[[:space:]]owner}'
